# docker-compose.yaml
version: '3'
services:
  amazon1:
    image: server
    environment:
      - APP=amazon
      - ENDPOINT=localhost:8081
    ports:
      - "8081:5000"

  amazon2:
    image: server
    environment:
      - APP=amazon
      - ENDPOINT=localhost:8082
    ports:
      - "8082:5000"

  amazon3:
    image: server
    environment:
      - APP=amazon
      - ENDPOINT=localhost:9081
    ports:
      - "9081:5000"

  apple1:
    image: server
    environment:
      - APP=apple
      - ENDPOINT=localhost:9082
    ports:
      - "9082:5000"
  
  # apple2:
  #   image: server
  #   environment:
  #     - APP=apple
  #     - ENDPOINT=localhost:9083
  #   ports:
  #     - "9083:5000"
    
  flipkart1:
    image: server
    environment:
      - APP=flipkart
      - ENDPOINT=localhost:1111
    ports:
      - "1111:5000"