# loadbalancer.yaml
hosts:
  - host: www.amazon.com
    servers:
      - localhost:8081
      - localhost:8082
      - localhost:9081
  - host: www.apple.com
    servers:
      - localhost:9082
      - localhost:9083
      - localhost:8888
  - host: www.flipkart.com
    servers:
      - localhost:1111
      - localhost:1212