# loadbalancer.yaml
# This file works like a DNS and also keeps the firewall rules
hosts:
  - host: www.amazon.com
    firewall_rules:
      ip_reject:
        - 47.125.74.69
        - 184.236.45.96
    servers:
      - localhost:8081
      - localhost:8082
      - localhost:9081
  - host: www.apple.com
    firewall_rules:
      ip_reject:
        - 192.168.29.142
        - 157.25.45.15
    servers:
      - localhost:9082
      - localhost:9083
      - localhost:8888
  - host: www.flipkart.com
    servers:
      - localhost:1111
      - localhost:1212